
server:
  port: 0000
  servlet:
    session:
      timeout: 3000

name: noteshelf-production

# spring datasource properties
spring:
  profiles: prod
  config:
    name: prod
  cache:
    type: redis
  datasource:
    url: jdbc:xxxx://xxxx:0000/xxxxxx?xxxxxxxxxxxxxxxxxxxxx  
    username: xxxxx
    password: xxxxx

    tomcat:
      max-wait: 20000
      max-active: 500
      max-idle: 20
      min-idle: 15 
      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id.new_generator_mappings: false
        format_sql: false
        
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session
  # configure below for time out. find whether the same is in seconds or minutes.
    timeout: 3600
     
            
  redis:
    host: xxxxxxx
    port: 0000
        
  data:
    mongodb:
      host: xxxxxx
      port: 000000  
      database: xxxxxxxxxxx  
      
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxxxxxx-xxxxxxx.xxxx.xxxxxxxxx.xxx
            client-secret: xxxxxx-xxxxxx-xxxxxxx
            scope: openid, profile, email, address, phone
          github:
            client-id: xxxxxxxxxxxxxxxxxxxx
            client-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  
             
  mail:
    host: xxxx.xxxx.xxx
    port: 000          
    username: xxxxxx@xxxxx.xxxx
    password: xxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
     
  
logging:
  level:
    org.springframework: INFO      
    
# Oauth2 related properties 

ank:
  oauth2:
   jwt:
     secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   applicationUrl: xxxx://xxxxxxxxxxxxx:0000/
   oauth2AuthenticationSuccessUrl: xxxx://xxxxxxx:0000/xxxxxxxxx?token= 
    
         
# hibernate logging disabled temporarily        
   # org.hibernate.SQL: DEBUG
   # org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
    
  

  
  
  
  
  
  
  
  
  
  
  
  