
# spring actuators  
# all web endpoints are available beneath the path /actuator with URLs of the form /actuator/{id}.   
# changing the form of the endpoint URLs from /actuator/{id} to /manage/{id}. For example, the URL info endpoint would become /manage/info.
  
management:
  server:
    port: 0000
    address: 127.0.0.1
  endpoints:
    web:
      base-path: /manage
  
logging:
  level:
    org.springframework: INFO      

         
# hibernate logging disabled temporarily        
   # org.hibernate.SQL: DEBUG
   # org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
    
spring:
  profiles:
    active: prod
    
   

  
  
  
  
  
  
  
  
  
  
  
  