package com.ank.apps.noteshelf.model;
// Generated Jun 15, 2018 6:59:13 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NsUserAuthDetail generated by hbm2java
 */
@Entity
@Table(name = "NS_USER_AUTH_DETAIL", catalog = "Note_shelf_DB")
public class NsUserAuthDetail implements java.io.Serializable {

	private Integer userAuthDetailId;
	private int userId;
	private String password;
	private String authType;
	private String active;
	private String locked;
	private Date createdDate;
	private Date updatedDate;

	public NsUserAuthDetail() {
	}

	public NsUserAuthDetail(int userId) {
		this.userId = userId;
	}

	public NsUserAuthDetail(int userId, String password, String authType, String active, String locked,
			Date createdDate, Date updatedDate) {
		this.userId = userId;
		this.password = password;
		this.authType = authType;
		this.active = active;
		this.locked = locked;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_AUTH_DETAIL_ID", unique = true, nullable = false)
	public Integer getUserAuthDetailId() {
		return this.userAuthDetailId;
	}

	public void setUserAuthDetailId(Integer userAuthDetailId) {
		this.userAuthDetailId = userAuthDetailId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "AUTH_TYPE", length = 50)
	public String getAuthType() {
		return this.authType;
	}

	public void setAuthType(String authType) {
		this.authType = authType;
	}

	@Column(name = "ACTIVE", length = 2)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "LOCKED", length = 2)
	public String getLocked() {
		return this.locked;
	}

	public void setLocked(String locked) {
		this.locked = locked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 26)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 26)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
