package com.ank.apps.noteshelf.model;
// Generated Apr 7, 2018 11:14:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NsLogin generated by hbm2java
 */
@Entity
@Table(name = "NS_LOGIN", catalog = "NS_USER")
public class NsLogin implements java.io.Serializable {

	private int loginId;
	private Integer userId;
	private String userName;
	private String password;

	public NsLogin() {
	}

	public NsLogin(int loginId) {
		this.loginId = loginId;
	}

	public NsLogin(int loginId, Integer userId, String userName, String password) {
		this.loginId = loginId;
		this.userId = userId;
		this.userName = userName;
		this.password = password;
	}

	@Id

	@Column(name = "LOGIN_ID", unique = true, nullable = false)
	public int getLoginId() {
		return this.loginId;
	}

	public void setLoginId(int loginId) {
		this.loginId = loginId;
	}

	@Column(name = "USER_ID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
