package com.ank.apps.noteshelf.model;
// Generated May 27, 2018 12:40:57 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NsNotesMetaData generated by hbm2java
 */
@Entity
@Table(name = "NS_NOTES_META_DATA", catalog = "Note_shelf_DB")
public class NsNotesMetaData implements java.io.Serializable {

	private Integer noteId;
	private int userId;
	private String noteNosqlId;
	private Date createdDate;
	private Date updatedDate;

	public NsNotesMetaData() {
	}

	public NsNotesMetaData(int userId) {
		this.userId = userId;
	}

	public NsNotesMetaData(int userId, String noteNosqlId, Date createdDate, Date updatedDate) {
		this.userId = userId;
		this.noteNosqlId = noteNosqlId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NOTE_ID", unique = true, nullable = false)
	public Integer getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Integer noteId) {
		this.noteId = noteId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "NOTE_NOSQL_ID", length = 45)
	public String getNoteNosqlId() {
		return this.noteNosqlId;
	}

	public void setNoteNosqlId(String noteNosqlId) {
		this.noteNosqlId = noteNosqlId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 26)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 26)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
