package com.ank.apps.noteshelf.model;
// Generated Apr 7, 2018 11:14:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NsUser generated by hbm2java
 */
@Entity
@Table(name = "NS_USER", catalog = "NS_USER", uniqueConstraints = { @UniqueConstraint(columnNames = "USERNAME"),
		@UniqueConstraint(columnNames = "EMAIL_ADDRESS") })
public class NsUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2725625022629421125L;
	private Integer userId;
	private String firstName;
	private String lastName;
	private String username;
	private String emailAddress;
	private String password;
	private String expired;
	private String locked;

	public NsUser() {
	}

	public NsUser(String firstName, String username, String password) {
		this.firstName = firstName;
		this.username = username;
		this.password = password;
	}

	public NsUser(String firstName, String lastName, String username, String emailAddress, String password,
			String expired, String locked) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.emailAddress = emailAddress;
		this.password = password;
		this.expired = expired;
		this.locked = locked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "EMAIL_ADDRESS", unique = true, length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EXPIRED", length = 1)
	public String getExpired() {
		return this.expired;
	}

	public void setExpired(String expired) {
		this.expired = expired;
	}

	@Column(name = "LOCKED", length = 1)
	public String getLocked() {
		return this.locked;
	}

	public void setLocked(String locked) {
		this.locked = locked;
	}

}
