package com.ank.noteshelf.model;
// Generated Jun 16, 2018 12:30:45 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NsUserRoles generated by hbm2java
 */
@Entity
@Table(name = "NS_USER_ROLES", catalog = "Note_shelf_DB")
public class NsUserRoles implements java.io.Serializable {

	private int roleId;
	private int userId;
	private String roleName;
	private Date createdDate;
	private Date updatedDate;

	public NsUserRoles() {
	}

	public NsUserRoles(int userId, String roleName) {
		this.userId = userId;
		this.roleName = roleName;
	}

	public NsUserRoles(int roleId, int userId, String roleName, Date createdDate, Date updatedDate) {
		this.roleId = roleId;
		this.userId = userId;
		this.roleName = roleName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 26)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 26)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
